base_url = "https://benburk.github.io"

title = "Ben Burk"
description = "A timeless blog theme"
compile_sass = false
highlight_code = true
generate_rss = true

[markdown]
highlight_code = true


[extra]
henry_links = [
    {url = "/about", name = "About"},
]
henry_github = "https://github.com/benburk"
# henry_twitter = "https://twitter.com/dhh"

mathjax = true